[tool.poetry]
name = "mg"
version = "0.1.0"
description = "Mirgovorit"
authors = ["Aleksey Inkov"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
django = "^4.2.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
