# Generated by Django 4.2.9 on 2024-01-29 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="count_recipe",
            new_name="count_cook",
        ),
    ]
